version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/pgdata:/pgdata
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=daylog
      - PGDATA=/pgdata
  api:
    build:
      context: ./api
    volumes:
      - ./api:/go/src/github.com/skippednote/daylog
    command: ./daylog
    ports:
      - "8080:8080"
    depends_on:
      - db
